In [3]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
# 성은 남자 나이는 평균 엠바크드는 s

### sklearn.preprocessing.LabelEncoder
* 

In [4]:
items = ['TV', '냉장고', '전자랜지', '컴퓨터', '선풍기', '선풍기', '믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [5]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자랜지' '컴퓨터']


In [6]:
print('디코딩 원본 값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본 값: ['전자랜지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [7]:
import pandas as pd
import numpy as np

In [8]:
Titanic = pd.read_csv("./train.csv")

In [9]:
Titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [10]:
# corona_df.drop("Unnamed: 0", axis = 1, inplace= True)
Titanic.drop("Pclass", axis = 1, inplace= True)
Titanic.drop("PassengerId", axis = 1, inplace= True)

In [11]:
Titanic.drop("Name", axis = 1, inplace= True)
Titanic.drop("SibSp", axis = 1, inplace= True)
Titanic.drop("Parch", axis = 1, inplace= True)
Titanic.drop("Ticket", axis = 1, inplace= True)
Titanic.drop("Fare", axis = 1, inplace= True)

In [12]:
Titanic.drop("Cabin", axis = 1, inplace= True)


In [13]:
Titanic.isna().sum()

Survived      0
Sex           0
Age         177
Embarked      2
dtype: int64

In [14]:
Titanic["Age"].mean()

29.69911764705882

In [15]:
Titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       714 non-null    float64
 3   Embarked  889 non-null    object 
dtypes: float64(1), int64(1), object(2)
memory usage: 28.0+ KB


In [16]:
Titanic["Age"]= Titanic["Age"].fillna(Titanic["Age"].mean())

In [17]:
Titanic["Embarked"]=Titanic["Embarked"].fillna('S')

In [18]:
Titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       891 non-null    float64
 3   Embarked  891 non-null    object 
dtypes: float64(1), int64(1), object(2)
memory usage: 28.0+ KB


In [19]:
# Sex. Eebarked Encoding
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
Titanic["Age"]=encoder.fit_transform(Titanic["Age"])

In [20]:
Titanic["Embarked"]=encoder.fit_transform(Titanic["Embarked"])

In [21]:
Titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Survived  891 non-null    int64 
 1   Sex       891 non-null    object
 2   Age       891 non-null    int64 
 3   Embarked  891 non-null    int32 
dtypes: int32(1), int64(2), object(1)
memory usage: 24.5+ KB


In [22]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [24]:
items = ['TV', '냉장고', '전자랜지', '컴퓨터', '선풍기', '선풍기', '믹서','믹서']

# 먼저 숫자값으로 변환을 위해 Lable Encoder 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환합니다.
labels = labels.reshape(-1,1)

# 원 - 핫 인코딩을 적용합니다.

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원 핫 인코딩 데이터')
print(oh_labels.toarray())
print('원 핫 인코딩 데이터 차원')
print(oh_labels.shape)

원 핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원 핫 인코딩 데이터 차원
(8, 6)
